### ISSUE TITLE
Accurate region constants?

### ISSUE THREAD

**Issue by briangru** [hagronnestad/leaf-display#1]
I noticed you're using the region constants for Europe and other countries that used to work with Nissan's version 1 of teh Leaf API's.  My understanding is with V2, the region name for the USA changed from "NNA" to "US".  However, I have no idea what happened with Europe.  Is this known to work with a European Leaf account?

**Comment by hagronnestad** [comment]
@briangru I got those constants from some example code somewhere, so I don't know if they're accurate or not. I'm in the EU and the code works for me as of today at least.

**Comment by briangru** [comment]
Great to know - thanks.
